apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-configmap
data:
    S3_BUCKET: "ziliscite-vid-1"
    S3_REGION: "ap-southeast-1"
    AMQP_HOST: "b-b96ce6cb-6f40-47e3-9208-78102caa3a82.mq.ap-southeast-1.amazonaws.com"
    AMQP_USERNAME: "ziliscite"
    AMQP_PORT: "5671"