apiVersion: v1
kind: ConfigMap
metadata:
    name: converter-configmap
data:
    # reference to localhost from kubernetes
    POSTGRES_HOST: "auth-db-mp4.cvmueuyaytim.ap-southeast-1.rds.amazonaws.com"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "ziliscite"
    POSTGRES_DB: "auth"
    S3_MP4_BUCKET: "ziliscite-vid-1"
    S3_MP3_BUCKET: "ziliscite-mp3"
    S3_REGION: "ap-southeast-1"
    S3_CLOUDFRONT_DISTRIBUTION: "your-distribution-id"
    AMQP_HOST: "b-b96ce6cb-6f40-47e3-9208-78102caa3a82.mq.ap-southeast-1.amazonaws.com"
    AMQP_USERNAME: "ziliscite"
    AMQP_PORT: "5671"
    AMQP_VIDEO_QUEUE_NAME: "video_queue"
    AMQP_NOTIFICATION_QUEUE_NAME: "notification_queue"