apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth
    labels:
        app: auth
spec:
    replicas: 2
    selector:
        matchLabels:
            app: auth
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 3
    template:
        metadata:
            labels:
                app: auth
        spec:
            # pull container from dockerhub
            containers:
              - name: auth
                image: ziliscite/video-to-mp4-auth
                imagePullPolicy: Always
                ports:
                    - containerPort: 5000
                envFrom:
                    - configMapRef:
                        name: auth-configmap
                    - secretRef:
                        name: auth-secrets